### ISSUE TITLE
Token management system

### ISSUE THREAD

**Issue by ricardomestre** [hotosm/oam-uploader-api#1]
## Sign in structure
- Logo
- Sign in form
  - email
  - password

## Signed in structure
- Logo
- Signed in user info (plus sign out action)
- Tokens list
  - Token key
  - Description (character limited)
  - Creation date
  - Expiration date
  - Status (active, blocked)
  - Actions (edit status, description and expiration date, delete) ?
- Add new
  - View fields above
  - Add button 

### Behavior
- Add inline (to the top of the list)
- Edit inline

## Future features
- Multiple users?
- Recover password system

**Comment by anandthakker** [comment]
@danielfdsilva I just put in a stub for the token management, so that I could have a dummy 'user' object to work with.  Check out: https://github.com/hotosm/oam-uploader-api/commit/082f200830640141505ffc2574100dbb1dfbcc6a

**Comment by anandthakker** [comment]
^ sorry, not token management, just the token *authentication*.
