### ISSUE TITLE
Handling partial failures

### ISSUE THREAD

**Issue by anandthakker** [hotosm/oam-uploader-api#13]
Currently, the API operates on `scene`s, each containing an array of images.  A scene has a status that can be queried on the front end (`initial`, `pending`, `errored`, `finished`).

What should we do in the case where we're processing an image, a few images have succeeded, but then one of them fails?

 - Should we treat the whole scene as `errored`?  If so, we'd presumably want to clean up the images we had already uploaded, but based on the timing it's very possible that the oam-catalog would already have harvested these.
 - Alternatively, should we make the status more granular, having it for each image instead of each scene?  Seems like this would be more complicated, UX-wise... but maybe better?  I don't know.

cc @smit1678 @ricardomestre @danielfdsilva @jflasher

**Comment by smit1678** [comment]
Yeah it seems that if there is the chance that it was already harvested by the catalog, then having more granular feedback is helpful and would be a pain to delete what's already been uploaded. This also reduces the amount of processing time to get the rest of the images online. 

Maybe a tabular readout in the email response of your submission?
