### ISSUE TITLE
Better quality thumbnails

### ISSUE THREAD

**Issue by anandthakker** [hotosm/oam-uploader-api#22]
We're currently generating PNG thumbnails -- nice for the transparency here there's no data, but pretty grainy even at ~400-500k per thumbnail.

I was getting erroneous results using JPG output before, but we should try getting that working and then compare.

**Comment by anandthakker** [comment]
After discussing this with @smit1678 and @olafveerman, it seems that the problem is likely just size, not file type.  Here are sample thumbnails with three different size settings:

~400 KB
![300](https://cloud.githubusercontent.com/assets/4974151/9408159/04920368-47de-11e5-9875-3355e370910c.png)

~700 KB
![600](https://cloud.githubusercontent.com/assets/4974151/9408162/08d56b72-47de-11e5-959e-96fcfe25b6db.png)

~1.1 MB
![900](https://cloud.githubusercontent.com/assets/4974151/9408163/0b4f1286-47de-11e5-8e48-b63c4f065d3f.png)

**Comment by smit1678** [comment]
@anandthakker looks good. Bigger size will be better for resolution. But 1.1mb is a lot. I think this is good for now but might be worth coming back in the future to get jpg working to have a larger size but smaller filesize.
