### ISSUE TITLE
OAM Stats Endpoints

### ISSUE THREAD

**Issue by DylanMoriarty** [hotosm/oam-uploader-api#34]
For the oam landing page, it'd be great to make sure api has endpoints we can use to calculate:

- [ ] Total # of imagery added to the database
- [ ] Total # of different sensors 
- [ ] Total # of providers

and additionally it could be interesting to see:

- [ ] Total Area covered by the imagery
- [ ] Total file size of the database

@nbumbarger, can you check the api and see how difficult it would be kick these out? The last two are of less of a priority, but if they're easy to get might be nice to have.

**Comment by smit1678** [comment]
A first version of this has been implemented: http://api.openaerialmap.org/analytics. Tracking image count, provider count, and sensor type count. We can revisit if we want to add these other metrics in at a later time.
