### ISSUE TITLE
Resolution is not calculated correctly

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-uploader-api#42]
All the imagery that was [uploaded recently](https://beta.openaerialmap.org/#/-73.93524169921875,18.411866765202845,9?date=month&resolution=high&_k=6hcpfl) for Hurricane Matthew response shows `RESOLUTION` as `0`.

Previous images like [these UAV ones in Tajikistan](https://beta.openaerialmap.org/#/71.71875,37.71859032558816,5/1231003?resolution=high&_k=6e0tod), show the resolution correctly.

**Comment by smit1678** [comment]
To start dig into this deeper: 

Recent DG imagery showing `0` gsd ([metadata file here](http://hotosm-oam.s3.amazonaws.com/uploads/2016-10-11/57fc935b84ae75bb00ec751b/scene/0/scene-0-image-0-DG-103001005F7D7A00-CLIP.tif_meta.json)): 
```
"gsd":0.0000044878248024438965
```

UAV imagery with correct gsd ([metadata file here](http://hotosm-oam.s3.amazonaws.com/uploads/2016-09-07/57cfd4b384ae75bb00ec7485/scene/0/scene-0-image-0-2016-08-18-fsd_darjomj_rgb_all_transparent_mosaic_rgb.tif_meta.json)): 

```
"gsd":0.16927
```

So this isn't a frontend issue but something to do with how the gsd is calculated during metadata generation. Need to look further at the geotiffs.

**Comment by mojodna** [comment]
It's a units thing. The DG imagery is in EPSG:4326, so that rather low number is in degrees rather than meters.

**Comment by mojodna** [comment]
Short version of comments in hotosm/oam-dynamic-tiler#9: gdalinfo-json needs to check the units in the data's CRS and not just assume that they're meters. If they're not meters, they need to be converted to meters appropriately and slotted into the `gsd` field.

**Comment by tombh** [comment]
Carrying on the thread from  hotosm/oam-dynamic-tiler#9

@mojodna said:
> gdalinfo-json uses node-gdal

Oh! That is both clarifying and confusing. I just saw the [`exec()`](https://github.com/scisco/gdalinfo-json/blob/develop/index.js#L92) shelling to `gdalinfo /vsicurl/` and assumed that that was approach taken by the whole module. So what's confusing is that `node-gdal` binds *directly* to `libgdal`'s C interface. So `node-gdal` has methods such as [`getLinearUnits()`](https://naturalatlas.github.io/node-gdal/classes/gdal.SpatialReference.html#method-getLinearUnits), or even more powerfully [`getAttrValue()`](https://naturalatlas.github.io/node-gdal/classes/gdal.SpatialReference.html#method-getAttrValue). This is because `libproj4` is a dependency of `libgdal`.

So the shelling and regexing in `gdalinfo-json` is curious considering those native, robust and simple `libgdal` methods are literally a few keystrokes away. I would assume that either the author is/was unaware of those method calls or has a compelling justification for not using them.

**Comment by mojodna** [comment]
A potential compelling justification is that "expensive" `libgdal` methods aren't async in `node-gdal`, so shelling out to `gdal` effectively achieves that.

**Comment by tombh** [comment]
Oh I don't understand. Expensive as in they take a long time? I've never experienced that. And also what's a specific example where aysynchronously calling `gdalinfo` wouyld be useful? Even then I would have thought the responsibility of concurrency should be separated somewhere else, namely OS-level processes, like a worker.

**Comment by mojodna** [comment]
`node-gdal` hasn't yet implemented threadpooling of heavy I/O processes, so it doesn't follow Node.js norms. (Not saying that it would be useful the way it's used now, just that that might have been the consideration when shelling out via `exec`.)

**Comment by tombh** [comment]
Hmm, I understand what your saying. But I just can't imagine that being the reason.

So right now, I don't see the use case for `gdalinfo-json`. It would be better to just depend on `node-gdal` in `oin-meta-generator` and get the relevant data using the `libgdal` interface. No need to prematurely optimise for concurrency.

**Comment by mojodna** [comment]
Totally, and it's not used in an interactive setting either (usually as a command line tool where it's not competing with anything else).

**Comment by tombh** [comment]
Yeah agreed. Ok, hopefully I can get this fixed next week then. Thanks Seth.

**Comment by tombh** [comment]
I can't remember if subscribers get notifications for related commits? Anyway, @mojodna, there's a new commit, it's rather significant, what are your thoughts?

**Comment by mojodna** [comment]
Not unless I'm explicitly mentioned in the commit. Thanks, I'll have a look!

**Comment by tombh** [comment]
Should we keep this issue open until the old imagery meta data has been updated, as per the original comment about the Hurricane Matthew imagery? That will require manually running scripts that incorporate the oin-meta-generator fix.

**Comment by mojodna** [comment]
From Slack:

```bash
#!/usr/bin/env bash

set -eo pipefail

aws s3 ls s3://${1}/ --recursive | \
  grep \.tif$ | \
  awk "{print \"s3://${1}/\" \$4}" | \
  while read src; do
    echo $src
    filename=$(basename $src)
    aws s3 cp $src .

    set +e
    aws s3 cp ${src%.tif}_meta.json orig.json
    set -e

    oin-meta-generator $filename > new.json

    if [[ -e orig.json ]]; then
      jq -s '.[0] * .[1]' orig.json new.json > meta.json
      aws s3 cp meta.json ${src%.tif}_meta.json
    else
      aws s3 cp new.json ${src%.tif}_meta.json
    fi

    rm -f $filename orig.json new.json meta.json
  done
```

Usage: `backfill-metadata.sh <bucket>`

Should be run from us-east-1 because it needs to download files from S3 in order to generate metadata from them.

**Comment by tombh** [comment]
Thanks Seth. just waiting to iron out `oin-meta-generator` issues...
