### ISSUE TITLE
API Docs don't load

### ISSUE THREAD

**Issue by mojodna** [hotosm/oam-uploader-api#47]
http://hotosm.github.io/oam-uploader-api/

Looks like missing dependencies.

**Comment by cgiovando** [comment]
Is this the same available here? https://docs.openaerialmap.org/uploader/getting-started

**Comment by mojodna** [comment]
No, though it's linked to from https://docs.openaerialmap.org/uploader/api-server/.

I'm assuming it's the specific API endpoints exposed by the code in this repo.
