### ISSUE TITLE
Is oam-uploader-api.herokuapp.com still in use?

### ISSUE THREAD

**Issue by mojodna** [hotosm/oam-uploader-api#48]
It's [referenced](https://github.com/hotosm/oam-uploader-api/blob/develop/package.json#L72) in the `apidoc` section of `package.json`.

**Comment by smit1678** [comment]
@mojodna No it's not actually. The very first version was running on heroku. Only thing in use connected to Heroku is the mLab mongodb.

**Comment by mojodna** [comment]
Gotcha. I'll leave this open for when someone comes through to do repository cleanup (so it can be removed from `package.json` and the app deleted from Heroku).

**Comment by smit1678** [comment]
Assigning this to me to help out with that.
