### ISSUE TITLE
Max workers within config.js

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-uploader-api#62]
Right now we have the `maxWorkers` set to only 1. Let's test and increase this to enable faster processing of the queue. 

@nbumbarger Have you tested this?

**Comment by nbumbarger** [comment]
I actually haven't tested it, but all of the processing files are sandboxed so I wouldn't expect any issues. How many threads does the instance provide?

**Comment by smit1678** [comment]
👍  For the t2.xlarge right now it looks like it has 4 cores and handled my test to bump it up to 4 max workers.
