### ISSUE TITLE
Review dockerization, add docker-compose file

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-uploader-api#63]
Confirm additions for new gdal work, mongodb, and other configuration. Enable the use of `docker-compose` with a `docker-compose.yml` file. 

See TM2 docker compose for example: https://github.com/hotosm/osm-tasking-manager2/blob/docker-2.13/docker-compose.yml.

**Comment by mojodna** [comment]
There's a `docker-compose.yml` included in #66.
